Repository rajeshsinha1997/task-manager-rest-java, pull requests merged in 2024-03, with the labels that each got.

#1 Feature - Created Initial Project Setup
  .gitignore
  tmr/pom.xml
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/dtos/generic/GenericErrorResponseDTO.java
  tmr/src/main/java/dtos/generic/GenericResponseDTO.java
  tmr/src/main/java/dtos/request/TaskPostRequestDTO.java
  tmr/src/main/java/dtos/response/TaskDataResponseDTO.java
  tmr/src/main/java/exceptions/InvalidRequestAttributeValueException.java
  tmr/src/main/java/models/TaskModel.java
  tmr/src/main/java/repositories/ITaskRepository.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
  tmr/src/main/java/services/TaskService.java
  tmr/src/main/java/utilities/CommonServletUtility.java
  tmr/src/main/java/utilities/CommonUtility.java
  tmr/src/main/java/utilities/DataValidationUtility.java
  tmr/src/main/webapp/WEB-INF/web.xml
  tmr/src/main/webapp/index.jsp
Labels: enhancement

#5 Feature - Added Docker Configuration
  .github/workflows/build_and_publish_docker_image.yml
  tmr/Dockerfile
  tmr/pom.xml
Labels: enhancement

#6 Migrating changes from Develop branch to Main branch
  .github/workflows/build_and_publish_docker_image.yml
  tmr/Dockerfile
  tmr/pom.xml
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/repositories/ITaskRepository.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
  tmr/src/main/java/services/TaskService.java
Labels: enhancement

#10 Added Fix For Issue - Bug: Request to GET /tasks returns 500 Internal Server Error
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
  tmr/src/main/java/services/TaskService.java
Labels: enhancement

#12 11 todo add GitHub action scripts for status checking
  .github/workflows/code_ql_analysis.yml
  .github/workflows/dependency_review.yml
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
Labels: enhancement

#13 Merge Changes from Develop Branch to the Main branch
  .github/workflows/code_ql_analysis.yml
  .github/workflows/dependency_review.yml
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
  tmr/src/main/java/services/TaskService.java
Labels: enhancement

#15 Feature - Implemented GET /tasks/{id} Endpoint
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/exceptions/InvalidRequestUrlException.java
  tmr/src/main/java/services/TaskService.java
  tmr/src/main/java/utilities/CommonServletUtility.java
  tmr/src/main/java/utilities/DataValidationUtility.java
Labels: enhancement

#19 Feature - Updated GitHub Actions Script to Build and Publish Docker Image Only Whenever a New Tag Has Been Created
  .github/workflows/build_and_publish_docker_image.yml
  tmr/pom.xml
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/exceptions/InvalidRequestUrlException.java
  tmr/src/main/java/services/TaskService.java
  tmr/src/main/java/utilities/CommonServletUtility.java
  tmr/src/main/java/utilities/DataValidationUtility.java
Labels: enhancement

#21 Feature - Implement DELETE/tasks/{id} Endpoint
  .github/workflows/build_and_publish_docker_image.yml
  tmr/pom.xml
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/repositories/ITaskRepository.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
  tmr/src/main/java/services/TaskService.java
Labels: enhancement

#22 Merge Changes from the Develop Branch to the Main Branch
  tmr/pom.xml
  tmr/postman_collection/task-manager-rest-api.postman_collection.json
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/repositories/ITaskRepository.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemory.java
  tmr/src/main/java/services/TaskService.java
Labels: enhancement

#25 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#27 Documentation - Updated README.md with Required Descriptions and Informations About the Project Repository
  README.md
Labels: documentation

#32 Feature - Add Dependency Injection into the Existing Implementation
  tmr/src/main/java/controllers/TaskServlet.java
  tmr/src/main/java/repositories/RepositoryFactory.java
  tmr/src/main/java/repositories/TaskRepositoryLocalMemoryImpl.java
  tmr/src/main/java/services/ServiceFactory.java
  tmr/src/main/java/services/TaskService.java
  tmr/src/test/java/controllers/TaskServletTest.java
  tmr/src/test/java/repositories/TaskRepositoryLocalMemoryTest.java
  tmr/src/test/java/services/TaskServiceTest.java
Labels: enhancement

#34 30 todo update existing test cases to improve coverage
  tmr/src/test/java/controllers/TaskServletIntegrationTest.java
  tmr/src/test/java/controllers/TaskServletTestBase.java
  tmr/src/test/java/controllers/TaskServletUnitTest.java
  tmr/src/test/java/services/TaskServiceTest.java
Labels: enhancement
